services:
  postgres:
    image: postgres
    container_name: postgres_bdPm
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kolie123
      POSTGRES_DB: gestionpublication

  adminer:
    image: adminer
    container_name: adminer_pm
    restart: always
    ports:
      - '8080:8080'

  douaneapp-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestionpublicationManagement-container
    restart: always
    ports:
      - '8090:8090'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gestionpublication
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: kolie123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres
